# Build validation

name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [21]
        os: [ubuntu-latest]
        distribution: [temurin]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Build and verify
        run: mvn -s ./.maven-settings.xml -Pcontinuous-integration -B -U clean verify
